add script and dockerfile
Duet-Technologies/point_click_care_sync pull request #1
Opened 2024-07-12 20:03 UTC by katieclaiborne-duet

2024-07-12 20:27 UTC, katieclaiborne-duet commented on Dockerfile
> +COPY . .
What does this line do?

2024-07-12 20:28 UTC, katieclaiborne-duet commented on export.py
> +bucket_path = "outbound"
We may want to add another level - maybe date?

2024-07-12 20:29 UTC, katieclaiborne-duet commented on export.py
> +destination_uri = "gs://{}/{}/{}".format(bucket_name, bucket_path, "duet_eligibility.csv")
Should we guarantee that the file name will be unique? Maybe add timestamp?

2024-07-12 21:22 UTC, katieclaiborne-duet commented on Dockerfile
> +ENTRYPOINT ["python", "export.py"]
Is it worth adding a Dockerfile at this point, or should we wait to orchestrate the export and push jobs together?

2024-07-14 19:37 UTC, JoeVieira requested changes

2024-07-14 19:37 UTC, JoeVieira commented on Dockerfile
> +ENTRYPOINT ["python", "export.py"]
I think that we'd want to use cloud function for this ( we don't need to manage the container, etc )

2024-07-15 14:57 UTC, katieclaiborne-duet commented on Dockerfile
> +ENTRYPOINT ["python", "export.py"]
Makes sense! I'll work on that today.

2024-07-15 14:57 UTC, katieclaiborne-duet commented
Closing, will reopen in broader "data exchange" repo.

2024-07-15 14:57 UTC, closed without merging